#!/usr/bin/env python3
"""
CP22B Controlled Email Test — Send exactly one test email to Roger only.

This script enforces CP22B safety constraints:
1. Requires explicit --send-one-test-email flag
2. Refuses to run if ALERT_ENABLE_EMAIL=true (production must remain disabled)
3. Refuses to run if recipient is not Roger's configured test address
4. Sends exactly one email with clear test markers
5. Does not send Telegram
6. Does not call Ross production routing
7. Redacts passwords and secrets in errors

Usage:
  python scripts/send_controlled_email_test.py --send-one-test-email
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add project root to path for imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

# Load .env from project root
load_dotenv(Path(__file__).resolve().parent.parent / ".env")


def check_preconditions() -> tuple[bool, str]:
    """
    Check all CP22B preconditions before sending.

    Returns:
        (passes, reason): True if all checks pass, plus reason if not
    """
    # Check 1: ALERT_ENABLE_EMAIL must be false (production email disabled)
    email_enabled = os.environ.get("ALERT_ENABLE_EMAIL", "").lower() in ("true", "1", "yes")
    if email_enabled:
        return False, "ALERT_ENABLE_EMAIL is true — production email is enabled. CP22B requires production email to remain disabled."

    # Check 2: All SMTP credentials must be present
    required_smtp_keys = [
        "SMTP_HOST",
        "SMTP_PORT",
        "SMTP_USE_SSL",
        "SMTP_USERNAME",
        "SMTP_PASSWORD",
        "ALERT_EMAIL_FROM",
        "ALERT_EMAIL_TO",
    ]

    missing = []
    for key in required_smtp_keys:
        val = os.environ.get(key, "").strip()
        if not val:
            missing.append(key)

    if missing:
        return False, f"Missing SMTP credentials: {', '.join(missing)}"

    # Check 3: Recipient must be Roger's configured test address
    recipient = os.environ.get("ALERT_EMAIL_TO", "").strip()
    expected_recipient = "fiske1945@4securemail.com"

    if recipient != expected_recipient:
        return False, f"Recipient is '{recipient}' but expected '{expected_recipient}'. CP22B only sends to Roger's test address."

    return True, "All preconditions met"


def send_controlled_test_email() -> int:
    """
    Send one controlled test email via generic SMTP.

    Returns:
        Exit code: 0 on success, 1 on failure
    """
    # Import here so precondition checks can run even if alerts module has issues
    try:
        from alerts.smtp_email import send_email
    except ImportError as exc:
        print(f"[FAIL] Failed to import alerts.smtp_email: {exc}")
        return 1

    # CP22B test email content
    subject = "[INSIDER TEST] CP22B controlled email test"

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    body = f"""CONTROLLED LIVE EMAIL TEST — CP22B
===================================

This is a one-time controlled test email.

Timestamp: {timestamp}
Production email alerts remain disabled.
No Telegram message was sent.
No trade was placed.

This email verifies:
✓ SMTP delivery channel is operational
✓ Email format renders correctly in mail client
✓ Subject line is professional and clear
✓ Production email routing remains disabled (ALERT_ENABLE_EMAIL=false)

Informational only. Not investment advice.

---
Generated by CP22B Controlled Email Test
scripts/send_controlled_email_test.py
"""

    recipient = os.environ.get("ALERT_EMAIL_TO")

    print("Sending CP22B controlled test email...")
    print(f"  Subject: {subject}")
    print(f"  Recipient: {recipient}")
    print(f"  Timestamp: {timestamp}")
    print()

    try:
        result = send_email(subject, body)
    except Exception as exc:
        # Redact any potential secrets in error messages
        error_msg = str(exc)
        if os.environ.get("SMTP_PASSWORD"):
            error_msg = error_msg.replace(os.environ.get("SMTP_PASSWORD", ""), "[REDACTED]")
        print(f"[FAIL] Exception during email send: {error_msg}")
        return 1

    if result["success"]:
        print("[OK] CP22B controlled test email sent successfully!")
        print()
        print(f"Sent from: {os.environ.get('ALERT_EMAIL_FROM')}")
        print(f"Sent to:   {recipient}")
        print()
        print("Next step: Roger should confirm receipt in 4SecureMail inbox.")
        return 0

    # Redact password from error messages
    error = result.get("error", "Unknown error")
    if os.environ.get("SMTP_PASSWORD"):
        error = error.replace(os.environ.get("SMTP_PASSWORD", ""), "[REDACTED]")

    print(f"[FAIL] Test email failed: {error}")
    return 1


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="CP22B Controlled Email Test — Send exactly one test email to Roger only",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
CP22B Safety Constraints:
  • Requires explicit --send-one-test-email flag
  • Refuses to run if ALERT_ENABLE_EMAIL=true
  • Refuses to run if recipient is not Roger's test address
  • Sends exactly one email with clear test markers
  • Does not send Telegram
  • Does not call Ross production routing

Example:
  python scripts/send_controlled_email_test.py --send-one-test-email
        """,
    )
    parser.add_argument(
        "--send-one-test-email",
        action="store_true",
        help="Send one controlled test email (requires explicit flag for safety)",
    )

    args = parser.parse_args()

    # Refuse to run without explicit flag
    if not args.send_one_test_email:
        print("[FAIL] Explicit --send-one-test-email flag required.")
        print()
        print("This is a controlled test that sends a live email.")
        print("Use --send-one-test-email to confirm you want to send.")
        return 1

    # Check all CP22B preconditions
    print("Checking CP22B preconditions...")
    print()

    passes, reason = check_preconditions()

    if not passes:
        print(f"[FAIL] Precondition check failed: {reason}")
        print()
        print("Cannot send controlled test email.")
        return 1

    print(f"[OK] {reason}")
    print()

    # Send the controlled test email
    return send_controlled_test_email()


if __name__ == "__main__":
    raise SystemExit(main())
